spring:
  application:
    name: controle-servicos-automotivos-sa
  profiles:
    active: local
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/controle-servicos
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_updates: true
        batch_versioned_data: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    out-of-order: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: public
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    context-path: /controle-servicos


springdoc:
  api-docs:
    path: /api-docs

app:
  auth:
    ignore-paths: /swagger-ui,/swagger-resources,/docs,/api-docs,/webjars,/info,/healthcheck,/health-check,/healthcheck/complete,/metrics,/error
    service-shared-secret: "teste-local"
