package br.com.vital.controle_servico.order_service.service.impl;

import br.com.vital.controle_servico.ai_voice.dto.ExtractedOrderDataDTO;
import br.com.vital.controle_servico.ai_voice.service.VoiceProcessingService;
import br.com.vital.controle_servico.customers.domain.Customer;
import br.com.vital.controle_servico.customers.repository.CustomerRepository;
import br.com.vital.controle_servico.order_service.domain.OrderService;
import br.com.vital.controle_servico.order_service.domain.OrderServiceStatus;
import br.com.vital.controle_servico.order_service.domain.OrderServiceType;
import br.com.vital.controle_servico.order_service.dto.OrderServiceResponseDTO;
import br.com.vital.controle_servico.order_service.mapper.OrderServiceMapper;
import br.com.vital.controle_servico.order_service.repository.OrderServiceRepository;
import br.com.vital.controle_servico.order_service.service.OrderAiIntegrationService;
import br.com.vital.controle_servico.tenants.config.TenantContext;
import br.com.vital.controle_servico.common.exception.UnauthorizedException;
import br.com.vital.controle_servico.vehicles.domain.Vehicle;
import br.com.vital.controle_servico.vehicles.repository.VehicleRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class OrderAiIntegrationServiceImpl implements OrderAiIntegrationService {

    private final CustomerRepository customerRepository;
    private final VehicleRepository vehicleRepository;
    private final OrderServiceRepository orderServiceRepository;
    private final VoiceProcessingService voiceProcessingService;

    @Override
    @Transactional
    public OrderServiceResponseDTO createDraftOrderByAudio(UUID customerId, UUID vehicleId, MultipartFile audio) {
        UUID tenantId = TenantContext.getTenantId();
        if (tenantId == null) {
            throw new UnauthorizedException();
        }

        Customer customer = customerRepository.findById(customerId)
                .filter(c -> tenantId.equals(c.getTenantId()))
                .orElseThrow(() -> new IllegalArgumentException("Customer not found with ID: " + customerId));

        Vehicle vehicle = vehicleRepository.findById(vehicleId)
                .filter(v -> tenantId.equals(v.getTenantId()))
                .orElseThrow(() -> new IllegalArgumentException("Vehicle not found with ID: " + vehicleId));

        ExtractedOrderDataDTO aiData = voiceProcessingService.processAudioToOrderData(audio);

        String inspectionNotes = buildInspectionNotes(aiData);

        OrderService draftOrder = OrderService.builder()
                .description("Automatic Draft generated by AI Voice Analysis")
                .type(OrderServiceType.ANALYSIS)
                .status(OrderServiceStatus.PENDING)
                .customerComplaint(aiData.getCustomerComplaint())
                .tenantId(tenantId)
                .inspectionNotes(inspectionNotes)
                .dateStart(LocalDate.now())
                .amount(BigDecimal.ZERO)
                .partsCost(BigDecimal.ZERO)
                .laborCost(BigDecimal.ZERO)
                .discountAmount(BigDecimal.ZERO)
                .quantityItems(0)
                .kmVehicleAt(0)
                .build();

        draftOrder.addCustomer(customer);
        draftOrder.addVehicle(vehicle);

        OrderService savedOrder = orderServiceRepository.saveAndFlush(draftOrder);

        return OrderServiceMapper.toResponseDTO(savedOrder);
    }

    private String buildInspectionNotes(ExtractedOrderDataDTO data) {
        StringBuilder notes = new StringBuilder();

        if (data.getSuggestedParts() != null && !data.getSuggestedParts().isEmpty()) {
            notes.append("=== Suggested Parts ===\n");
            data.getSuggestedParts().forEach(part ->
                notes.append(String.format("- %s (%.2f %s)\n", part.getName(), part.getQuantity(), part.getUnit()))
            );
        }

        if (data.getSuggestedServices() != null && !data.getSuggestedServices().isEmpty()) {
            if (!notes.isEmpty()) {
                notes.append("\n");
            }
            notes.append("=== Suggested Services ===\n");
            data.getSuggestedServices().forEach(service ->
                notes.append(String.format("- %s (%.2f %s)\n", service.getName(), service.getQuantity(), service.getUnit()))
            );
        }

        return notes.toString();
    }
}
